version: '3'

services:
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8081:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
    ports:
      - 5432:5432

  service.auth:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: service.auth
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: postgres://test:test@db:5432/testdb?sslmode=disable
      SECRET: secret

    depends_on:
      - db
      - adminer
